### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by telip007** [facebook/facebook-sdk-swift#111]
I have a question. Can I parse the authToken to WKWebView to use Facebook Comments Plugin in it? I've been searching for a solution for one month now but couldn't find a solution and I need to finish this project. :)

**Comment by nlutsenko** [comment]
Hey @telip007, unfortunately the answer is "you can try, but I am not sure it will work".
The better place for this question would be [Stack Overflow](http://stackoverflow.com/questions/tagged/facebook+or+facebook-graph-api), and there is even a wide community there that will be able to help you, since this issue tracker is dedicated purely to things around Facebook Swift SDK.
