### ISSUE TITLE
OpenGraph in Swift

### ISSUE THREAD

**Issue by shu-ua** [facebook/facebook-sdk-swift#132]
Hello. I can not use the `OpenGraph` in Swift. `OpenGraphShareContent` does not confirm to type `ContentProtocol`, so I can't use `ShareDialog` and other methods.

Does anyone use `OpenGraph` in Swift?
Sample from here - https://developers.facebook.com/docs/swift/sharing/open-graph-content
Are not compilable too.

**Comment by RPCarter53** [comment]
This issue can be worked around with the following simple extension. The association to the ContentProtocol is missing in the original source.

extension OpenGraphShareContent : ContentProtocol {
    }

Beyond this however other problems will arise due to a faulty initiator for OpenGraphPropertyName. The initiator with suggested corrections is..

  public init?(_ string: String) {
    // let components = string.characters.split(separator: ":")
    let components = string.characters.split(separator: ":", maxSplits: 1) // suggested alternative
    guard components.count >= 2 else {
      return nil
    }

    self.namespace = String(components[0])
    self.name = String(components[1])   // suggested alternaive

    // The following original gives array index out of range and an invalid build of name
    //let subcharacters = components[1 ... components.count]
    //self.name = subcharacters.reduce("", { $0 + ":" + String($1) })
  }
