### ISSUE TITLE
Cannot Log initiatedCheckout Event

### ISSUE THREAD

**Issue by ninjudd** [facebook/facebook-sdk-swift#141]
When I try to log an `initiatedCheckout` event, like this:
```
AppEventsLogger.log(AppEvent.initiatedCheckout())
```
I get the following error: `Generic parameter 'T' could not be inferred`

I've also tried passing a number for the optional `itemCount` parameter:
```
AppEventsLogger.log(AppEvent.initiatedCheckout(itemCount: 1))
```
but no luck: `Cannot convert value of type 'Int' to expected argument type 'T?'`

**Comment by nlutsenko** [comment]
This is quite tricky...
So the reason it happens, is due to the fact that we require an `UnsignedInteger` to be passed in, but  `Int` by itself, which is the default type here actually doesn't conform to the `UnsignedInteger` protocol requirement.

What you want is to do to fix it is:
```swift
AppEventsLogger.log(AppEvent.initiatedCheckout(itemCount: UInt(1)))
```

If you have any other suggestion on how to fix it, whilst at the same time persisting the requirement for unsigned integer type on the argument - please let me know, but this is the safest approach so far that I was able to find.
