### ISSUE TITLE
Get Current profile of user

### ISSUE THREAD

**Issue by ALAxHxC** [facebook/facebook-sdk-swift#145]
Hello,

For example in objective c with sdk Facebook , when I want retrieve information profile of user I can user:

`[FBSDKProfile currentProfile]`

How I can do this , in Facebook sdk to Swift?

**Comment by KarthikSankar29** [comment]
Hi AlaxHxC,

Please check this documentation : [https://goo.gl/QZ5QzA](https://goo.gl/QZ5QzA).
Its as same as Objective-C ,  

`FBSDKProfile.currentProfile()`

**Comment by ALAxHxC** [comment]
Thanks , but when I try to access the information:


> `        FBSDKProfile.current().firstName`



> fatal error: unexpectedly found nil while unwrapping an Optional value
> 2017-04-10 16:35:17.746259-0500 ProcIOS[395:65909] fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by aodhol** [comment]
@ALAxHxC You either need to make sure the profile is loaded before you use it or you could load it asynchronously with a callback:

```
FBSDKProfile.loadCurrentProfile(completion: { (profile, error) in
                profile
                print("loaded: \(profile?.firstName)")
})
```

In your case I think the exception is being thrown because the profile isn't yet available when you attempt to access it (there's some other setup you may need to do), and the SDK being Objective-C uses implicitly unwrapped optionals where nullability specifiers weren't specified!

**Comment by galblank** [comment]
there is no loadCurrentProfile in FBSDKProfile
