### ISSUE TITLE
Make PermissionRepresentable protocol public

### ISSUE THREAD

**Issue by jablair** [facebook/facebook-sdk-swift#192]
Has there been any consideration of making the `PermissionRepresentable` protocol public, along with the accompanying implementations in `PublishPermission` and `ReadPermission`?

Similar to #91, I'm thinking this could aid the transition between the Read/Publish permissions and generic Permission type.

As far as I can tell, there's currently no way to check if the current AccessToken contains a permission without using the raw string value - i.e.:

`AccessToken.current?.grantedPermissions?.contains("public_profile")`

I'd like it if there was some way to let the compiler validate the permission name and do something like:

`AccessToken.current?.grantedPermissions?.contains(ReadPermission.publicProfile.permissionValue)`

**Comment by philipengberg** [comment]
I absolutely agree on this.

And similarly to #91, I want to compare the granted / declined permissions with the ones I requested for. That's not currently possible since I have to pass in a **array** of `ReadPermission`s but get back a **set** of `Permission`s. Since there's no access to the `permissionValue` of the `ReadPermission` these two cannot be compared.

Ideally *you* would accept a `Set<ReadPersmission>` and return a `Set<ReadPermission>` for both accepted and declined permissions so that you can easily compare like this fx:

```swift
var minimumReadPermissions: Set<ReadPermission> {
    return [.publicProfile]
}
    
var readPermissions: [ReadPermission] {
    return Set<ReadPermission>([.email, .userFriends]).union(minimumReadPermissions)
}

func login(from viewController: UIViewController) -> FacebookCredentials {
    loginManager.logIn(readPermissions: self.readPermissions, viewController: viewController, completion: { (result) in
        switch result {
        case .success(let grantedPermissions, let declinedPermissions, let token):
            if !declinedPermissions.isDisjoint(with: self.minimumReadPermissions) {
                // We cannot continue from here, inform user that the following is necessary:
                let declinedNecessaryPermissions = s.minimumReadPermissions.intersection(declinedPermissions)
            } else {
                // We're all good to continue
            }
        }
    })
}
```

This is all possible in the old SDK since it's all just strings anyway. I don't see why we can't make that work here as well 🙂

**Comment by philipengberg** [comment]
@nlutsenko Is this repository still being maintained? Activity seems awkwardly low 🤔

**Comment by AndrewSB** [comment]
@jablair that seems like a great idea. If you make a PR, we'd almost definitely merge it in
