### ISSUE TITLE
BUG on navbar color

### ISSUE THREAD

**Issue by themythIOS** [facebook/facebook-sdk-swift#24]
i set app delegate custom navbar to use pattern image.

UINavigationBar.appearance().barTintColor = UIColor(patternImage: UIImage(named: "tileNavBar.png")!)

then when you tap facebook login button, it will return error.

A fixed would change the color to use RGB values.

**Comment by nlutsenko** [comment]
Just tested this locally via SwiftCatalog sample app (it's included in the repo), and even though I can reproduce it no problem - I don't believe this is something we can fix, since the crash happens in `SFSafariViewController`, which is part of SafariServices.framework, which is outside of our control (it's built into the system starting from iOS 9).

I would suggest changing the appearance on case by case basis, and not for all `UINavigationBar`s in the application, or not using UIColor with a pattern image.
If you look for the same error (for example [here](https://www.google.com/search?q=Only+RGBA+or+White+color+spaces+are+supported+in+this+situation&gws_rd=ssl)), you will notices that a lot of people are running into the same scenario regardless of Facebook SDK.

Also, the following source code can reproduce the issue and has the same crash.
```swift
let controller = SFSafariViewController(URL: NSURL(string: "https://github.com")!)
self.presentViewController(controller, animated: true, completion: nil)
```
