### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by enagorny** [facebook/facebook-sdk-swift#26]
When swift 3 support will be released?
Is it possible to use current facebook-sdk-swift with swift3 project?

**Comment by nlutsenko** [comment]
This is a really good question!
Our plan is to add Swift 3 support the moment it goes GM, meaning sometime late in August/September (depends on Apple, not us). In the meantime - you are very welcome to use the Swift 3 migration tool on the current set of source code to update it to Swift 3. There shouldn't be a lot of violations that need to be fixed.

Another potential thing that can happen is we get Swift 3 branch that you can use in the meantime, but there is not going to be explicit support on it, since it's going to be work in progress.

**Comment by enagorny** [comment]
I ended up using Obj-C lib for now. And will migrate to official Swift 3 facebook-sdk-swift right after release or even beta.

**Comment by phuonglm86** [comment]
How about now?

**Comment by RyuuSenpai** [comment]
i still have a problem when adding fb SDK (linker comand failed with exit code 1 (use -v to see invocation) that is the error taht appear when add the sdk
