### ISSUE TITLE
Error after adding Pod

### ISSUE THREAD

**Issue by fboulegue** [facebook/facebook-sdk-swift#31]
I did try the new released Facebook SDK for Swift [Github][1], added but after 

> pod 'FacebookCore'

But after 

> pod install 

I get a error, see attached image

[![error][2]][2]

Are there more steps needed?

  [1]: https://github.com/facebook/facebook-sdk-swift
  [2]: http://i.stack.imgur.com/3whV5.png

**Comment by camdendevelopers** [comment]
Hey @fboulegue. This error happened to me when using FBSDK (Objective-C pods) and after doing some research, I found that this could be fixed by going to Build Settings > Type "Modular" > Select "Yes" for the setting "Allow non-modular include in Frameworks modules". Afterwards just clean and run!

Facebook functionality for apps is so hard to debug, but hopefully this helps! Let me know if this fixes your issue.


<img width="1078" alt="screen shot 2016-07-25 at 10 15 33 am" src="https://cloud.githubusercontent.com/assets/8826948/17106392/c41b6da0-5250-11e6-8291-0c5cb8c29721.png">

**Comment by nlutsenko** [comment]
Hey guys,

This can happen for number of reasons, but the most common one: stale Xcode ModuleCache.
I would recommend the following:
- Deleting Xcode's DerivedData (including from Trash and restarting Xcode).
- Making sure that there is no ObjC frameworks anywhere in the framework search paths

If the issue still arises for you - please attach a repro project that we can use to reproduce the issue.
If it contains any private or sensitive info that you want to hide - you can always reach me at nlutsenko(at)fb.com or file a bug report via developers.facebook.com.

**Comment by iamrohit1** [comment]
I got the same error. Fix mentioned by @camdendevelopers did not do the trick. I have attached a sample project producing this error. Don't mind the name of that project please.
Using  XCode 7.3
[dubbyFB.zip](https://github.com/facebook/facebook-sdk-swift/files/391453/dubbyFB.zip)

**Comment by nlutsenko** [comment]
@iamrohit1, indeed the project attached fails to compile with that error.

And the solution is - update your `CocoaPods` gem locally.
The version you are using is `0.39`, the version we support is `1.0.0+`.

Here is the fixed project (just used CocoaPods 1.0.1 and everything worked like a charm).
[dubbyFB.zip](https://github.com/facebook/facebook-sdk-swift/files/391545/dubbyFB.zip)

Please run `sudo gem update cocoapods` (you can skip sudo, depending on your ruby gems installation of course) and re-run `pod install` or `pod update`.
