### ISSUE TITLE
Carthage update fails on ObjC SDK, due to `git` vs `https` schemes.

### ISSUE THREAD

**Issue by iStopped** [facebook/facebook-sdk-swift#48]
I'm trying to install this SDK for the ParseFacebookUtils, but I encounter the same error. The shell output is this:

<img width="640" alt="schermata 2016-08-31 alle 11 44 05" src="https://cloud.githubusercontent.com/assets/910971/18123947/7707b9d2-6f70-11e6-981f-2dc6ccdfb344.png">

The build works if I remove the Facebook dependencies.

**Comment by thertzelle** [comment]
I'm getting the exact same message on my machine, first time i've tried to use carthage to install this framework.

**Comment by thertzelle** [comment]
I submitted this pull request to the master repository in attempts to get the issue resolved:

https://github.com/facebook/facebook-ios-sdk/pull/839

**Comment by nlutsenko** [comment]
Blocked `git://` scheme - that sounds very weird!
It is a great idea to use `https` instead of `git` for submodules, we should definitely do that instead to avoid issues like this.

Going to ping some folks internally, but overall, that PR should go out together with the next release of ObjC SDK (likely in about 3 weeks).

In the meantime - I would suggest trying to get `git://` scheme unblocked for you or use a different internet connection.

**Comment by nlutsenko** [comment]
Quick update here... Looks like ObjC SDK 4.15.1 got released, but the schemes got overriden again from `https` back to `git` 😭 
Going to take a look at the ObjC SDK and make sure that it's back in the proper state, so you guys can checkout via Carthage over https.

**Comment by nlutsenko** [comment]
This should be almost fixed with 4.16 (my patch for FBTweaks there didn't make the cut 😢 ).
The core installation part should be fixed though, so I would recommend everyone to give it a try.

**Comment by nlutsenko** [comment]
ObjC SDK 4.17 was finally released and it includes the fix for `https` scheme.
Sorry folks it took us a while to fully and finally fix this.
It is going to be available in the next SDK version.
