### ISSUE TITLE
Is this lib safe to use for production?

### ISSUE THREAD

**Issue by LarsWith** [facebook/facebook-sdk-swift#76]
I wonder if this lib is safe to use for production since it says (beta)

**Comment by nlutsenko** [comment]
Hey @LarsWith, it is safe to use in production.

The beta label, at the current stage, it mostly to ensure that everyone is aware that there might be drastic changes coming to the API and be ready for it.

If you have suggestions/feature requests - now is the best time to file them, since we are more flexible changing the APIs at the current stage.
