### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by tecexpert** [facebook/facebook-sdk-swift#80]
error:

```
'FBSDKCoreKit/FBSDKButton.h' file not found
Could not build Objective-C module 'FBSDKLoginKit'
```

![screen shot 2016-10-19 at 3 05 13 pm](https://cloud.githubusercontent.com/assets/17078055/19513545/e2591e56-960d-11e6-8e00-0b29171b497b.png)

**Comment by nlutsenko** [comment]
Hey @tecexpert, unfortunately, you would need to be slightly more descriptive about the error.
Specifically:
- What is your installation method (CocoaPods, Carthage, manual, etc)?
- Since it looks like you are using `FacebookLogin` and `FacebookCore`, can you make sure you have both checked out and linked?
- Does cleaning Xcode's DerivedData and ModuleCache help in any way?

Please re-open the issue or open a new one with more details.

**Comment by nefy55** [comment]
I get the same mistake. What I do is not improving my work.
1) I am loading with Cocoapods. Pods I have installed at work

Pod 'FBSDKCoreKit', '~ 4.8.0'
Pod 'FBSDKShareKit', '~> 4.8.0'
   Pod 'FBSDKLoginKit', '~ 4.8.0'

2) I am cleaning the deilvered data.
3) I am getting an error installing only the facebook SDK. The project is not working.
