### ISSUE TITLE
Improve ambiguous `logIn()` function names in LoginManager.

### ISSUE THREAD

**Issue by nitisha1** [facebook/facebook-sdk-swift#95]
Hi,
I've integrated facebook-sdk-swift manually in my ios project in xcode8 following documents (https://developers.facebook.com/docs/swift/getting-started).  I'm getting error "Ambiguous reference to memeber logIn(_:viewController:completion:)"on 
 

` loginManager.logIn(["public_profile","email"], viewController: self) { loginResult in
            switch loginResult {
            case .Failed(let error):
                print(error)
            case .Cancelled:
                print("User cancelled login.")
            case .Success(let grantedPermissions, let declinedPermissions, let accessToken):
                print("Logged in!")
            }
`
what i've done wrong any help please?

**Comment by nlutsenko** [comment]
Hey @nitisha1,

Unfortunately, without more code around this - it could be very tricky to help you.
Though, I believe I have an idea on why this is failing...
Looks like you are using plain strings for permissions, which can be ambiguous, as the Swift compiler won't know whether to use 
```swift
func logIn(_ permissions: [ReadPermission] = [.publicProfile],
                    viewController: UIViewController? = nil,
                    completion: ((LoginResult) -> Void)? = nil)
```
or
```swift
func logIn(_ permissions: [PublishPermission] = [.publishActions],
                    viewController: UIViewController? = nil,
                    completion: ((LoginResult) -> Void)? = nil)
```

Here is the updated method signature that I recommend replacing it with:
```swift
loginManager.logIn([ .public_profile, .email ], viewController: self) {
...
}
```

This will eliminate the ambiguousness and will let you compile.
Also, let me keep this open as a follow-up, since I believe we can improve these method names.

**Comment by nitisha1** [comment]
@nlutsenko thanks a lot ,it worked.

**Comment by FoxTime07** [comment]
don't work for me

**Comment by bj97301** [comment]
I am not using strings and still getting this error.

**Comment by mkval** [comment]
I'm getting the same error, too. Can't compile. Why don't we just rename the methods? Something like `func logIn(withReadPermissions perms: [ReadPermission], ...)` and `func logIn(withPublishPermissions perms: [PublishPermission], ...)`.

**Comment by JaapWeijland** [comment]
Me too.

**Comment by krishcdbry** [comment]
Me too
